version: 0.2  
phases:  
  install:
    commands:
      - aws cloudformation package --template-file spam.yaml --s3-bucket spam-artifact --output-template-file spam-filter.yaml
artifacts:  
  type: zip
  files:
    - spam-filter.yaml
